<?php
$config = array(
'title' => 'Fleen-Host',
'description' => 'Хостинг игровых серверов SAMP / CRMP',
'keywords' => 'бесплатный хостинг самп, fleen host, samp, mta, big host, maze, dragon host, lg host, maze host, флин хост, флен хост, swag host, майз хост, самп хост, крмп хост',
'url' => 'https://fleen-host.ru/',
'db_type'		=>		'mysql',
'db_hostname'	=>		'localhost',
'db_username'	=>		'admin',
'db_password' => '7BSA2MTICiZr9mQc',
'db_database'	=>		'hostin',
'mail_sender' => 'FLEEN-HOST',
'mail_from' => 'admin@fleen-host.ru',
'public' => '210554805',
'logo' => '/logo.png',
'webhost' => '1',
'aaio' => '1',
'freekassa' => '1',
'yandexkassa' => '1',
'yk_login' => '4100118884973887',
'yk_password1' => 'XykZB4uaj2lQ9FooSjoNMTb5',
'aaio_id' => '3332fd5f-32cf-47a0-84eb-6553bd1bb8c9',
'aaio_secret1' => 'a29405d9edd117dcc6eb2f004813f488',
'aaio_secret2' => '71be76955517cee5ac6369e8cec58c04',
'fk_server'	 =>	'https://pay.freekassa.com/',
'fk_login' => '38645',
'fk_password1' => 'D-9*@0g=1at%v-{',
'fk_password2' => 'ROF=eIB=gW%sha6',
'vk_app_status' => '1',
'vk_app_id' => '8112345',
'vk_app_secretkey' => 'u0lO058M6xcDKxURxOAM',
'serv_test' => '1',
'offline' => '0',
'offline_res' => 'Хостинг временно закрыт на обслуживание',
'recaptcha' => '6Ldmx9wjAAAAACDM1Xy9PFxePMF26lgdBQSyrFUW',
'secret_recaptcha' => '6Ldmx9wjAAAAANGCnzyX0IgYLoa5E65ZBwWN5nEk',
'VK_bot' => '1',
'VK_confirmationToken' => 'f169b3e4',
'VK_token' => 'vk1.a.JTqHrNFN_XH7RRWOSomH2Qf7P43oLq8ZcGAbRt_5xW8GM2tsid1RG-3INPTQFm7qIZRq0uZ0qTUgjJ-NZdUUQgFKeTGPCf-zOF-3crl_9rk7aK38DohKCsHpkpdvO7kZ7mLn8L_jm5_jCpjRqrCDm4CIkyGBjOrfrzTI5h9lln2fxkWM2LxnhiN9P3btAOaA',
'VK_secretKey' => 'HjvkTYUNjvkfkl',
'portPrice' => '50',
'register' => '1',
'bonus1' => '10',
'bonus2' => '30',
'bonus3' => '60',
'bonus4' => '100',
'status_hostinpl' => '0',
'close' => 'off',
'ref_percent' => '5',
'bonus_percent' => '5',
'ip' => 'localhost',
'user' => 'root',
'password' => 'tBxJx4OeccjJ'
);
?>